version: '3.8'
services:

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/movies
      - python-deps:/movies/venv
    ports:
      - "8080:8080"

volumes:
  python-deps:
